# Generated by Django 3.1.6 on 2021-03-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
